# Generated by Django 4.1 on 2022-09-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belajarApp', '0003_jumlahpenghasiilanortu'),
    ]

    operations = [
        migrations.CreateModel(
            name='JumlahPenghasilanOrtu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JumlahPenghasilanOrtu', models.CharField(max_length=100)),
                ('bobot', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='JumlahTanggunganOrangTua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JumlahTanggunganOrangTua', models.CharField(max_length=100)),
                ('bobot', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='NilaiRatarataRaport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NilaiRatarataRaport', models.CharField(max_length=100)),
                ('bobot', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='PresentaseKehadiranSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PresentaseKehadiranSiswa', models.CharField(max_length=100)),
                ('bobot', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Prestasiyangdiraih',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prestasiyangdiraih', models.CharField(max_length=100)),
                ('bobot', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.DeleteModel(
            name='JumlahPenghasiilanOrtu',
        ),
    ]
