# Generated by Django 4.1 on 2022-09-09 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belajarApp', '0004_jumlahpenghasilanortu_jumlahtanggunganorangtua_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('NISN', models.CharField(max_length=10)),
                ('jenis_kelamin', models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], default=1, max_length=30)),
                ('Jumlah_Anak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belajarApp.jumlahtanggunganorangtua')),
                ('Nilai_ratarata_raport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belajarApp.nilairatarataraport')),
                ('Penghasilan_orangtua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belajarApp.jumlahpenghasilanortu')),
                ('Presentase_kehadiran_siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belajarApp.presentasekehadiransiswa')),
                ('Prestasi_yang_pernah_diraih', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belajarApp.prestasiyangdiraih')),
            ],
        ),
    ]
