# Generated by Django 4.1.1 on 2022-09-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belajarApp', '0005_datasiswa'),
    ]

    operations = [
        migrations.CreateModel(
            name='PembobotanKriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kriteria', models.CharField(default='', max_length=10, null=True)),
                ('Name', models.CharField(max_length=100)),
                ('bobot', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.RenameField(
            model_name='datasiswa',
            old_name='Name',
            new_name='Nama',
        ),
        migrations.RenameField(
            model_name='jumlahpenghasilanortu',
            old_name='JumlahPenghasilanOrtu',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='jumlahtanggunganorangtua',
            old_name='JumlahTanggunganOrangTua',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='nilairatarataraport',
            old_name='NilaiRatarataRaport',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='presentasekehadiransiswa',
            old_name='PresentaseKehadiranSiswa',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='prestasiyangdiraih',
            old_name='Prestasiyangdiraih',
            new_name='Name',
        ),
    ]
