# Generated by Django 4.1.1 on 2022-09-15 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belajarApp', '0007_alter_pembobotankriteria_kriteria'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasilAnalisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rangking', models.IntegerField()),
                ('Poin', models.DecimalField(decimal_places=2, max_digits=3)),
                ('NISN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belajarApp.datasiswa')),
            ],
        ),
    ]
