# Generated by Django 4.1.1 on 2022-09-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belajarApp', '0008_hasilanalisa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pembobotankriteria',
            old_name='Kriteria',
            new_name='kriteria',
        ),
        migrations.AddField(
            model_name='pembobotankriteria',
            name='Keterangan',
            field=models.CharField(choices=[('Cost', 'Cost'), ('Benefit', 'Benefit')], default=1, max_length=30),
        ),
    ]
