# Generated by Django 4.0.2 on 2022-09-21 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belajarApp', '0011_alter_hasilanalisa_nisn'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasilanalisa',
            name='JenisKelamin',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hasilanalisa',
            name='Nama',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
