# Generated by Django 4.1.1 on 2022-09-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belajarApp', '0006_pembobotankriteria_rename_name_datasiswa_nama_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembobotankriteria',
            name='Kriteria',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
