# Generated by Django 4.1.1 on 2022-09-15 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belajarApp', '0009_rename_kriteria_pembobotankriteria_kriteria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasiswa',
            old_name='Jumlah_Anak',
            new_name='Jumlah_tanggungan_orang_tua',
        ),
    ]
